name: fl
channels:
  - pytorch
  - defaults
dependencies:
  - astroid=2.11.7=py310hca03da5_0
  - blas=1.0=openblas
  - bottleneck=1.3.5=py310h96f19d2_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py310h1a28f6b_1002
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2022.07.19=hca03da5_0
  - certifi=2022.9.24=py310hca03da5_0
  - cffi=1.15.1=py310h22df2f2_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py310h834c97f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h04105a8_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h1192e45_0
  - gettext=0.21.0=h826f4ad_0
  - giflib=5.2.1=h1a28f6b_0
  - gmp=6.2.1=hc377ac9_3
  - gnutls=3.6.15=h887c41c_0
  - icu=68.1=hc377ac9_0
  - idna=3.3=pyhd3eb1b0_0
  - isort=5.9.3=pyhd3eb1b0_0
  - jpeg=9e=h1a28f6b_0
  - kiwisolver=1.4.2=py310hc377ac9_0
  - lame=3.100=h1a28f6b_0
  - lazy-object-proxy=1.6.0=py310h1a28f6b_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcxx=12.0.0=hf6beb65_1
  - libdeflate=1.8=h1a28f6b_5
  - libffi=3.4.2=hc377ac9_4
  - libgfortran=5.0.0=11_2_0_he6877d6_26
  - libgfortran5=11.2.0=he6877d6_26
  - libiconv=1.16=h1a28f6b_2
  - libidn2=2.3.1=h1a28f6b_0
  - libopenblas=0.3.20=hea475bc_0
  - libopus=1.3=h1a28f6b_1
  - libpng=1.6.37=hb8d0fd4_0
  - libtasn1=4.16.0=h1a28f6b_0
  - libtiff=4.4.0=had003b8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.2.2=h68602c7_0
  - libwebp-base=1.2.2=h1a28f6b_0
  - libxml2=2.9.14=h8c5e841_0
  - llvm-openmp=12.0.0=haf9daa7_1
  - lz4-c=1.9.3=hc377ac9_0
  - matplotlib=3.5.1=py310hca03da5_1
  - matplotlib-base=3.5.1=py310hc377ac9_1
  - mccabe=0.7.0=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h1a28f6b_3
  - nettle=3.7.3=h84b5d62_1
  - numexpr=2.8.3=py310h5a06f4b_0
  - numpy=1.23.1=py310h220015d_0
  - numpy-base=1.23.1=py310h742c864_0
  - openh264=1.8.0=h98b2900_0
  - openssl=1.1.1q=h1a28f6b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py310hc377ac9_0
  - pillow=9.2.0=py310h4d1bdd5_1
  - pip=22.1.2=py310hca03da5_0
  - platformdirs=2.5.2=py310hca03da5_0
  - psutil=5.9.0=py310h1a28f6b_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pylint=2.14.5=py310hca03da5_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pysocks=1.7.1=py310hca03da5_0
  - python=3.10.4=hbdb9e5c_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.12.1=py3.10_0
  - pytz=2022.1=py310hca03da5_0
  - readline=8.1.2=h1a28f6b_1
  - requests=2.28.1=py310hca03da5_0
  - setuptools=61.2.0=py310hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h1058600_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=py310hca03da5_0
  - tomlkit=0.11.1=py310hca03da5_0
  - torchvision=0.13.1=py310_cpu
  - tornado=6.1=py310h1a28f6b_0
  - tqdm=4.64.0=py310hca03da5_0
  - typing_extensions=4.3.0=py310hca03da5_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.11=py310hca03da5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py310h1a28f6b_0
  - x264=1!152.20180806=h1a28f6b_0
  - xz=5.2.5=h1a28f6b_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.2.12=h5a0b063_2
  - zstd=1.5.2=h8574219_0
  - pip:
    - pyyaml==6.0
    - torchmetrics==0.9.3
